### ISSUE TITLE
Legacy-encrypter issue - Trying to upgrade my Laravel 5.2 to 5.3 and then 5.3 to 5.4

### ISSUE THREAD

**Issue by SimonH-MG** [laravel/legacy-encrypter#1]
The thing is we'll have a 5.2 version deployed on the field. So when I'll do a pull I'll upgrade it straight to 5.4 and I need the legacy encrypter for 5.4 to update my users' passwords.

However when I'm doing the upgrade to 5.4 my composer is giving this error that says the legacy-encrypter requires 5.3.*

Problem 1
    - Conclusion: don't install laravel/framework v5.4.13
    - Conclusion: don't install laravel/framework v5.4.12
    - Conclusion: don't install laravel/framework v5.4.11
    - Conclusion: don't install laravel/framework v5.4.10
    - Conclusion: don't install laravel/framework v5.4.9
    - Conclusion: don't install laravel/framework v5.4.8
    - Conclusion: don't install laravel/framework v5.4.7
    - Conclusion: don't install laravel/framework v5.4.6
    - Conclusion: don't install laravel/framework v5.4.5
    - Conclusion: don't install laravel/framework v5.4.4
    - Conclusion: don't install laravel/framework v5.4.3
    - Conclusion: don't install laravel/framework v5.4.2
    - Conclusion: don't install laravel/framework v5.4.1
    - laravel/legacy-encrypter v1.0.0 requires illuminate/support 5.3.* -> satisfiable by laravel/framework[v5.3.30], illuminate/support[v5.3.0, v5.3.16, v5.
    - laravel/legacy-encrypter v1.0.0 requires illuminate/support 5.3.* -> satisfiable by laravel/framework[v5.3.30], illuminate/support[v5.3.0, v5.3.16, v5.
    - don't install laravel/framework v5.4.0|don't install illuminate/support v5.3.0
    - don't install laravel/framework v5.4.0|don't install illuminate/support v5.3.16
    - don't install laravel/framework v5.4.0|don't install illuminate/support v5.3.23
    - don't install laravel/framework v5.4.0|don't install illuminate/support v5.3.4
    - Can only install one of: laravel/framework[v5.4.0, v5.3.30].
    - Installation request for laravel/framework 5.4.* -> satisfiable by laravel/framework[v5.4.0, v5.4.1, v5.4.10, v5.4.11, v5.4.12, v5.4.13, v5.4.2, v5.4.3
    - Installation request for laravel/legacy-encrypter ~1.0 -> satisfiable by laravel/legacy-encrypter[v1.0.0].

Thanks for your help.

**Comment by fabiosussetto** [comment]
@SimonH-MG got into the same problem, how did you fix it in the end?

**Comment by SimonH-MG** [comment]
I copied the raw files to my project. @fabiosussetto

**Comment by fabiosussetto** [comment]
@SimonH-MG thanks, I ended up doing the same.
